### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by cassiel74** [sammachin/sun2000_rs485#1]
Hi, does this work on SUN2000L-4.6KTL also?

(sorry for posting here in the issue)

**Comment by sammachin** [comment]
Hey @cassiel74 

To be honest I have no idea! I managed to find a doc with the MODBUS commands for the model I had, the 12KTL, its a much bigger and different looking unit see https://solar.huawei.com/en/download?p=%2F-%2Fmedia%2FSolar%2Fattachment%2Fpdf%2Feu%2Fdatasheet%2FSUN2000-8-12KTL.pdf

So you might need to experiment, one thing I should point out is that my inverter is 3phase so in some responses around the mains output I'll have 3 values, whereas a single phase unit would only have one. 

Sorry can't be much more help than that!
